profile:
  parameters:
    gcp:
      project_id: shifra-test-452800
    bigquery:
      dataset: FIRST_FLOW_DEV
      location: US

  defaults:
    - kind: Flow
      name:
        regex: .*
      spec:
        data_plane:
          connection_name: bigquery_data_plane
